POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Test Blog",
  "author": "Admin",
  "url": "localhost",
  "likes": 10
}

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Another Test Blog",
  "author": "Admin",
  "url": "localhost",
  "likes": 4
}